# Generated by Django 4.0.5 on 2022-06-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.CharField(choices=[('technology', 'technology'), ('art', 'art'), ('fashion', 'fashion'), ('architecture', 'architecture')], default='technology', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
