# Generated by Django 4.0.5 on 2022-06-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0003_project_categories_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='categories',
            new_name='category',
        ),
    ]
