# Generated by Django 4.0.5 on 2022-06-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0004_rename_categories_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
